export enum COMMANDS {
  PING = 'lame-ping',
  USER = 'lame-user',
  SERVER = 'lame-server',
  KANYE = 'kanye',
  ACTIVITY = 'lame-activity',
  DAD_JOKE = 'lame-dad-joke',
  GEEK_JOKE = 'lame-geek-joke',
  TRUMP = 'trump',
  ASSHOLE = 'asshole-gift',
  WHY_ASSHOLE = 'asshole-why',
  THANKS = 'thanks',
  RANDOM_BS = 'lame-random-bs',
  TEXT_FACE = 'lame-random-text-face',
  FACT = 'lame-fact',
}
